### ISSUE TITLE
Code Review Session

### ISSUE THREAD

**Issue by FrancoRosa** [ioilmio/form#3]

**Comment by idgm5** [comment]
Just a few observations with  your Lints:

```
.form>div, p {
    text-align: center;
}
```

Always try to give some space between elements. Instead of:

`form>div,p`

should be 
`.form > div, p `

Also in your div "terms" and "disclaimer", you could benefit with some padding and reduce your <p> tags width to 90-95% to give those small design details.

**Comment by FrancoRosa** [comment]
> Just a few observations with your Lints:
> 
> ```
> .form>div, p {
>     text-align: center;
> }
> ```
> 
> Always try to give some space between elements. Instead of:
> 
> `form>div,p`
> 
> should be
> `.form > div, p `
> 
> Also in your div "terms" and "disclaimer", you could benefit with some padding and reduce your
> 
> tags width to 90-95% to give those small design details.

Thank you man, you all are the boss
